# Generated by Django 5.0.4 on 2024-04-10 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comensal', models.CharField(max_length=100)),
                ('cantidad', models.PositiveBigIntegerField()),
                ('estado', models.CharField(choices=[('pd', 'pendiente'), ('et', 'entregado')], default='pd', max_length=2)),
                ('preparacion', models.CharField(choices=[('lv', 'llevar'), ('rs', 'consumir en restaurante')], default='rs', max_length=2)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productos')),
            ],
            options={
                'ordering': ['-fecha_pedido'],
            },
        ),
    ]
