# Generated by Django 5.0.4 on 2024-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidos_estado_alter_pedidos_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='preparacion',
            field=models.CharField(choices=[('llevar', 'llevar'), ('consumir en restaurante', 'consumir en restaurante')], default='consumir en restaurante', max_length=23),
        ),
    ]
