# Generated by Django 5.0.4 on 2024-04-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedidos_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('preparacion', 'preparacion'), ('entregado', 'entregado')], default='preparacion', max_length=11),
        ),
    ]
