# Generated by Django 5.0.4 on 2024-04-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='observaciones',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
